services:
  - type: web
    name: anime-walls-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        fromService:
          type: web
          name: anime-walls-frontend
          property: host

  - type: web
    name: anime-walls-frontend
    runtime: static
    staticPublishPath: ./
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: anime-walls-backend
          property: host